### ISSUE TITLE
AssertionError: assert self.resource_path

### ISSUE THREAD

**Issue by ivan** [chfoo/wpull#241]
I think this happened 2d 16h 20m into `!a http://log.b-a.link/ --pipeline=pipeline:ace877d357e08d096d3baad6589de64a`.  I see the same exception elsewhere in my log, so it may have also happened on another job.  I can't determine which job, because no rsync output follows.

```
ERROR Fatal exception.
Traceback (most recent call last):
  File "/home/archivebot/.local/lib/python3.4/site-packages/wpull/app.py", line 121, in run
    yield From(self._builder.factory['Engine']())
  File "/home/archivebot/.local/lib/python3.4/site-packages/trollius/tasks.py", line 251, in _step
    result = coro.throw(exc)
  File "/home/archivebot/.local/lib/python3.4/site-packages/wpull/engine.py", line 273, in __call__
    yield From(self._run_workers())
  File "/home/archivebot/.local/lib/python3.4/site-packages/trollius/tasks.py", line 253, in _step
    result = coro.send(value)
  File "/home/archivebot/.local/lib/python3.4/site-packages/wpull/engine.py", line 65, in _run_workers
    task.result()
  File "/home/archivebot/.local/lib/python3.4/site-packages/trollius/futures.py", line 287, in result
    raise self._exception
  File "/home/archivebot/.local/lib/python3.4/site-packages/trollius/tasks.py", line 251, in _step
    result = coro.throw(exc)
  File "/home/archivebot/.local/lib/python3.4/site-packages/wpull/engine.py", line 144, in _run_worker
    yield From(self._process_item(item))
  File "/home/archivebot/.local/lib/python3.4/site-packages/trollius/tasks.py", line 251, in _step
    result = coro.throw(exc)
  File "/home/archivebot/.local/lib/python3.4/site-packages/wpull/engine.py", line 318, in _process_item
    yield From(self._process_url_item(url_record))
  File "/home/archivebot/.local/lib/python3.4/site-packages/trollius/tasks.py", line 251, in _step
    result = coro.throw(exc)
  File "/home/archivebot/.local/lib/python3.4/site-packages/wpull/engine.py", line 343, in _process_url_item
    yield From(self._processor.process(url_item))
  File "/home/archivebot/.local/lib/python3.4/site-packages/trollius/tasks.py", line 251, in _step
    result = coro.throw(exc)
  File "/home/archivebot/.local/lib/python3.4/site-packages/wpull/processor/delegate.py", line 27, in process
    raise Return((yield From(self.web_processor.process(url_item))))
  File "/home/archivebot/.local/lib/python3.4/site-packages/trollius/tasks.py", line 251, in _step
    result = coro.throw(exc)
  File "/home/archivebot/.local/lib/python3.4/site-packages/wpull/processor/web.py", line 125, in process
    raise Return((yield From(session.process())))
  File "/home/archivebot/.local/lib/python3.4/site-packages/trollius/tasks.py", line 251, in _step
    result = coro.throw(exc)
  File "/home/archivebot/.local/lib/python3.4/site-packages/wpull/processor/web.py", line 208, in process
    yield From(self._process_loop())
  File "/home/archivebot/.local/lib/python3.4/site-packages/trollius/tasks.py", line 251, in _step
    result = coro.throw(exc)
  File "/home/archivebot/.local/lib/python3.4/site-packages/wpull/processor/web.py", line 265, in _process_loop
    exit_early = yield From(self._fetch_one(self._request))
  File "/home/archivebot/.local/lib/python3.4/site-packages/trollius/tasks.py", line 251, in _step
    result = coro.throw(exc)
  File "/home/archivebot/.local/lib/python3.4/site-packages/wpull/processor/web.py", line 310, in _fetch_one
    self._web_client_session.fetch(callback=response_callback)
  File "/home/archivebot/.local/lib/python3.4/site-packages/trollius/tasks.py", line 251, in _step
    result = coro.throw(exc)
  File "/home/archivebot/.local/lib/python3.4/site-packages/wpull/http/web.py", line 165, in fetch
    response = yield From(session.fetch(request))
  File "/home/archivebot/.local/lib/python3.4/site-packages/trollius/tasks.py", line 251, in _step
    result = coro.throw(exc)
  File "/home/archivebot/.local/lib/python3.4/site-packages/wpull/http/client.py", line 79, in fetch
    yield From(stream.write_request(request, full_url=full_url))
  File "/home/archivebot/.local/lib/python3.4/site-packages/trollius/tasks.py", line 251, in _step
    result = coro.throw(exc)
  File "/home/archivebot/.local/lib/python3.4/site-packages/wpull/abstract/stream.py", line 16, in wrapper
    raise Return((yield From(func(self, *args, **kwargs))))
  File "/home/archivebot/.local/lib/python3.4/site-packages/trollius/tasks.py", line 255, in _step
    result = next(coro)
  File "/home/archivebot/.local/lib/python3.4/site-packages/wpull/http/stream.py", line 87, in write_request
    data = request.to_bytes()
  File "/home/archivebot/.local/lib/python3.4/site-packages/wpull/http/request.py", line 50, in to_bytes
    assert self.resource_path
AssertionError
CRITICAL Sorry, Wpull unexpectedly crashed. Please report this problem to the authors at Wpull's issue tracker so it may be fixed. If you know how to program, maybe help us fix it? Thank you for helping us help you help us all.
```

**Comment by chfoo** [comment]
```
2229582 2015-02-09 21:24:55,005 - wpull.processor.web - INFO - Fetching ‘http://www.sesamestreet.org/cms-static/flappy_bert/assets/sounds/bert-ernie.ogg’.
2229583 2015-02-09 21:24:55,053 - wpull.processor.web - INFO - Fetched ‘http://www.sesamestreet.org/cms-static/flappy_bert/assets/sounds/bert-ernie.ogg’: 200 OK. Length:
2229584 2015-02-09 21:24:55,238 - wpull.processor.web - INFO - Fetching ‘http://www.sesamestreet.org/cms-static/flappy_bert/assets/sounds/bert-laugh.ogg’.
2229585 2015-02-09 21:24:55,356 - wpull.processor.web - INFO - Fetching ‘http://www.sesamestreet.org/cms-static/flappy_bert/assets/sounds/bert-ernie.mp3’.
2229586 2015-02-09 21:24:55,450 - wpull.processor.web - INFO - Fetching ‘http://www.sesamestreet.org/cms-static/flappy_bert/assets/images/bert-hands.png’.
2229587 2015-02-09 21:24:55,468 - wpull.processor.web - INFO - Fetched ‘http://www.sesamestreet.org/cms-static/flappy_bert/assets/sounds/bert-laugh.ogg’: 200 OK. Length:
2229588 2015-02-09 21:24:55,542 - wpull.processor.web - INFO - Fetched ‘http://www.sesamestreet.org/cms-static/flappy_bert/assets/images/bert-hands.png’: 200 OK. Length:
2229589 2015-02-09 21:24:55,603 - wpull.processor.web - INFO - Fetched ‘http://www.sesamestreet.org/cms-static/flappy_bert/assets/sounds/bert-ernie.mp3’: 200 OK. Length:
2229590 2015-02-09 21:24:55,960 - wpull.processor.web - INFO - Fetching ‘http://www.sesamestreet.org/cms-static/flappy_bert/assets/images/street-sign.png’.
2229591 2015-02-09 21:24:56,065 - wpull.processor.web - INFO - Fetching ‘http://staging.flappybird.io/img/logo.png’.
2229592 2015-02-09 21:24:56,173 - wpull.processor.web - INFO - Fetching ‘http://staging.flappybird.io/fonts/FB.eot’.
2229593 2015-02-09 21:24:56,205 - wpull.processor.web - INFO - Fetched ‘http://www.sesamestreet.org/cms-static/flappy_bert/assets/images/street-sign.png’: 200 OK. Length
2229594 2015-02-09 21:24:56,497 - wpull.processor.web - INFO - Fetched ‘http://staging.flappybird.io/fonts/FB.eot’: 200 OK. Length: 3426 [application/vnd.ms-fontobject].
2229595 2015-02-09 21:24:56,542 - wpull.processor.web - INFO - Fetched ‘http://staging.flappybird.io/img/logo.png’: 200 OK. Length: 4387 [image/png].
2229596 2015-02-09 21:24:56,706 - wpull.processor.web - INFO - Fetching ‘http://staging.flappybird.io/fonts/FB.svg’.
2229597 2015-02-09 21:24:56,906 - wpull.processor.web - INFO - Fetching ‘http://staging.flappybird.io/fonts/FB.ttf’.
2229598 2015-02-09 21:24:56,979 - wpull.processor.web - INFO - Fetching ‘http://staging.flappybird.io/fonts/FB.woff’.
2229599 2015-02-09 21:24:56,985 - wpull.processor.web - INFO - Fetched ‘http://staging.flappybird.io/fonts/FB.svg’: 200 OK. Length: 11072 [image/svg+xml].
2229600 2015-02-09 21:24:57,050 - wpull.processor.web - INFO - Fetched ‘http://staging.flappybird.io/fonts/FB.ttf’: 200 OK. Length: 8856 [application/x-font-ttf].
2229601 2015-02-09 21:24:57,180 - wpull.processor.web - INFO - Fetched ‘http://staging.flappybird.io/fonts/FB.woff’: 200 OK. Length: 4080 [application/x-font-woff].
2229602 2015-02-09 21:24:57,393 - wpull.processor.web - INFO - Fetching ‘http://staging.flappybird.io/assets/img/add-to-leaderboard.png’.
2229603 2015-02-09 21:24:57,519 - wpull.processor.web - INFO - Fetching ‘http://staging.flappybird.io/assets/img/ground.png’.
2229604 2015-02-09 21:24:57,627 - wpull.processor.web - INFO - Fetched ‘http://staging.flappybird.io/assets/img/add-to-leaderboard.png’: 301 Moved Permanently. Length: 0
2229605 2015-02-09 21:24:57,784 - wpull.processor.web - INFO - Fetching ‘http://staging.flappybird.io/assets/img/share.png’.
2229606 2015-02-09 21:24:57,890 - wpull.processor.web - INFO - Fetched ‘http://staging.flappybird.io/assets/img/ground.png’: 301 Moved Permanently. Length: 0 [none].
2229607 2015-02-09 21:24:57,973 - wpull.processor.web - INFO - Fetching ‘http://staging.flappybird.io/.’.
2229608 2015-02-09 21:24:57,977 - wpull.app - ERROR - Fatal exception.
```
