### ISSUE TITLE
AttributeError: 'RootTransaction' object has no attribute '_execute_on_connection'

### ISSUE THREAD

**Issue by ivan** [chfoo/wpull#254]
11 hours into `!a https://www.polaroidblipfoto.com --no-offsite-links`:

```
200 OK https://d3ba8mq6xd4ncz.cloudfront.net/9212191804a43cc4cd98ee2.96173532.jpg
200 OK https://d2rf1ftrp2hqm5.cloudfront.net/8663de6e40610af6.jpg
200 OK https://d1zkpmdxaytijy.cloudfront.net/16274177194a43d0baa441d2.90048358.jpg
200 OK https://d3ba8mq6xd4ncz.cloudfront.net/16786200634a43d016e61371.63495700.jpg
200 OK https://d3jf2jipiivcgq.cloudfront.net/16274177194a43d0baa441d2.90048358.jpg
200 OK https://d1zkpmdxaytijy.cloudfront.net/7034256414a441361e73682.20672641.jpg
ERROR Fatal exception.
Traceback (most recent call last):
  File "/home/archivebot/.local/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 835, in execute
    meth = object._execute_on_connection
AttributeError: 'RootTransaction' object has no attribute '_execute_on_connection'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/archivebot/.local/lib/python3.4/site-packages/wpull/app.py", line 128, in run
    yield From(self._builder.factory['Engine']())
  File "/home/archivebot/.local/lib/python3.4/site-packages/trollius/tasks.py", line 251, in _step
    result = coro.throw(exc)
  File "/home/archivebot/.local/lib/python3.4/site-packages/wpull/engine.py", line 278, in __call__
    yield From(self._run_workers())
  File "/home/archivebot/.local/lib/python3.4/site-packages/trollius/tasks.py", line 253, in _step
    result = coro.send(value)
  File "/home/archivebot/.local/lib/python3.4/site-packages/wpull/engine.py", line 67, in _run_workers
    task.result()
  File "/home/archivebot/.local/lib/python3.4/site-packages/trollius/futures.py", line 287, in result
    raise self._exception
  File "/home/archivebot/.local/lib/python3.4/site-packages/trollius/tasks.py", line 251, in _step
    result = coro.throw(exc)
  File "/home/archivebot/.local/lib/python3.4/site-packages/wpull/engine.py", line 146, in _run_worker
    yield From(self._process_item(item))
  File "/home/archivebot/.local/lib/python3.4/site-packages/trollius/tasks.py", line 251, in _step
    result = coro.throw(exc)
  File "/home/archivebot/.local/lib/python3.4/site-packages/wpull/engine.py", line 327, in _process_item
    yield From(self._process_url_item(url_record))
  File "/home/archivebot/.local/lib/python3.4/site-packages/trollius/tasks.py", line 251, in _step
    result = coro.throw(exc)
  File "/home/archivebot/.local/lib/python3.4/site-packages/wpull/engine.py", line 384, in _process_url_item
    yield From(self._processor.process(url_item))
  File "/home/archivebot/.local/lib/python3.4/site-packages/trollius/tasks.py", line 251, in _step
    result = coro.throw(exc)
  File "/home/archivebot/.local/lib/python3.4/site-packages/wpull/processor/delegate.py", line 27, in process
    raise Return((yield From(self.web_processor.process(url_item))))
  File "/home/archivebot/.local/lib/python3.4/site-packages/trollius/tasks.py", line 251, in _step
    result = coro.throw(exc)
  File "/home/archivebot/.local/lib/python3.4/site-packages/wpull/processor/web.py", line 123, in process
    raise Return((yield From(session.process())))
  File "/home/archivebot/.local/lib/python3.4/site-packages/trollius/tasks.py", line 251, in _step
    result = coro.throw(exc)
  File "/home/archivebot/.local/lib/python3.4/site-packages/wpull/processor/web.py", line 215, in process
    yield From(self._process_loop())
  File "/home/archivebot/.local/lib/python3.4/site-packages/trollius/tasks.py", line 251, in _step
    result = coro.throw(exc)
  File "/home/archivebot/.local/lib/python3.4/site-packages/wpull/processor/web.py", line 274, in _process_loop
    exit_early, wait_time = yield From(self._fetch_one(self._request))
  File "/home/archivebot/.local/lib/python3.4/site-packages/trollius/tasks.py", line 253, in _step
    result = coro.send(value)
  File "/home/archivebot/.local/lib/python3.4/site-packages/wpull/processor/web.py", line 339, in _fetch_one
    action = self._handle_response(request, response)
  File "/home/archivebot/.local/lib/python3.4/site-packages/wpull/processor/web.py", line 441, in _handle_response
    self._url_item.set_value(status_code=response.status_code)
  File "/home/archivebot/.local/lib/python3.4/site-packages/wpull/item.py", line 192, in set_value
    self._url_table.update_one(self._url, **kwargs)
  File "/home/archivebot/.local/lib/python3.4/site-packages/wpull/database/wrap.py", line 72, in update_one
    return self.url_table.update_one(*args, **kwargs)
  File "/home/archivebot/.local/lib/python3.4/site-packages/wpull/database/sqltable.py", line 178, in update_one
    session.execute(query)
  File "/usr/lib/python3.4/logging/__init__.py", line 1021, in formatException
  File "/home/archivebot/.local/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 839, in execute
    type(object))
sqlalchemy.exc.InvalidRequestError: Unexecutable object type: <class 'sqlalchemy.engine.base.RootTransaction'>
CRITICAL Sorry, Wpull unexpectedly crashed.
CRITICAL Please report this problem to the authors at Wpull's issue tracker so it may be fixed. If you know how to program, maybe help us fix it? Thank you for helping us help you help us all.
```

**Comment by chfoo** [comment]
Maybe this is related to #186 or #189.
