### ISSUE TITLE
Crashing: AssertionError.

### ISSUE THREAD

**Issue by ethus3h** [chfoo/wpull#293]
Hello! This crashes reproducibly on this crawl in ArchiveBot. Seems to be at that URL that it dies.... Reporting per the suggestion in the log. :)

200 OK https://www.sfsite.com/
  DUPE https://www.sfsite.com/
      OF https://www.sfsite.com/home.htm
ERROR Fatal exception.
Traceback (most recent call last):
  File "/home/archivebot/.local/lib/python3.4/site-packages/wpull/app.py", line 128, in run
    yield From(self._builder.factory['Engine']())
  File "/home/archivebot/.local/lib/python3.4/site-packages/trollius/tasks.py", line 251, in _step
    result = coro.throw(exc)
  File "/home/archivebot/.local/lib/python3.4/site-packages/wpull/engine.py", line 278, in __call__
    yield From(self._run_workers())
  File "/home/archivebot/.local/lib/python3.4/site-packages/trollius/tasks.py", line 253, in _step
    result = coro.send(value)
  File "/home/archivebot/.local/lib/python3.4/site-packages/wpull/engine.py", line 67, in _run_workers
    task.result()
  File "/home/archivebot/.local/lib/python3.4/site-packages/trollius/futures.py", line 287, in result
    raise self._exception
  File "/home/archivebot/.local/lib/python3.4/site-packages/trollius/tasks.py", line 251, in _step
    result = coro.throw(exc)
  File "/home/archivebot/.local/lib/python3.4/site-packages/wpull/engine.py", line 146, in _run_worker
    yield From(self._process_item(item))
  File "/home/archivebot/.local/lib/python3.4/site-packages/trollius/tasks.py", line 251, in _step
    result = coro.throw(exc)
  File "/home/archivebot/.local/lib/python3.4/site-packages/wpull/engine.py", line 327, in _process_item
    yield From(self._process_url_item(url_record))
  File "/home/archivebot/.local/lib/python3.4/site-packages/trollius/tasks.py", line 255, in _step
    result = next(coro)
  File "/home/archivebot/.local/lib/python3.4/site-packages/wpull/engine.py", line 386, in _process_url_item
    assert url_item.is_processed
AssertionError
CRITICAL Sorry, Wpull unexpectedly crashed.
CRITICAL Please report this problem to the authors at Wpull's issue tracker so it may be fixed. If you know how to program, maybe help us fix it? Thank you for helping us help you help us all.
Finished WgetDownload for Item 
Starting RelabelIfAborted for Item 
Starting WriteInfo for Item 
Finished WriteInfo for Item 
Starting MoveFiles for Item 
Finished MoveFiles for Item 
Starting RsyncUpload for Item 
sending incremental file list
urls-archive.org-(2015-11-22n10)%20converted.urls%20v4.txt-shallow-20151123-143038-bklvj-urls.txt

         32,768   1%    0.00kB/s    0:00:00  
      2,909,530 100%   40.35MB/s    0:00:00 (xfr#1, to-chk=1/2)
urls-archive.org-(2015-11-22n10)%20converted.urls%20v4.txt-shallow-20151123-143038-bklvj.json

            417 100%    5.99kB/s    0:00:00  
            417 100%    5.99kB/s    0:00:00 (xfr#2, to-chk=0/2)
sent 169,393 bytes  received 53 bytes  37,654.67 bytes/sec
total size is 2,909,947  speedup is 17.17
Finished RsyncUpload for Item 
Starting StopHeartbeat for Item 
Finished StopHeartbeat for Item 
Starting MarkItemAsDone for Item

**Comment by ethus3h** [comment]
I'm seeing this in grab-site, too, so I've filed an issue there... https://github.com/ludios/grab-site/issues/51

**Comment by JustAnotherArchivist** [comment]
I just experienced this error as well with version 1.2.3. Restarting wpull (I always use `--database`) caused it to crash again immediately. I ran some tests with `--debug` and figured out that the exception was triggered by the URL `clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B`. After manually marking it as skipped in the database, wpull resumed fine.

I wonder how that URL even ended up in the database though. It was extracted from `<object classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="425" height="350">`, but it should've been filtered out immediately by the SchemeFilter.

**Comment by ivan** [comment]
Is there any way to reproduce this using some known-bad site?

**Comment by JustAnotherArchivist** [comment]
If I remember correctly, the case I described in my comment above – I don't know whether this is the same as the original report since that did not include which URL triggered the exception – was caused by an `accept_url` hook which didn't check the scheme. So it should be fairly simple to reproduce this: set up an HTTP server on localhost (or mock wpull's network code), throw an HTML page with an unsupported scheme in a URL on it, then archive it with wpull and a hook `def accept_url(*args): return True`.
