### ISSUE TITLE
Encoding problems with URLs. URLs have to be encoded.

### ISSUE THREAD

**Issue by Arkiver2** [chfoo/wpull#298]
From IRC:
```
<arkiver>~/.local/bin/grab-site http://www.eqmweekly.com.af/international/8288-سردرگمی-در-سیاست-خارجی-ترکیه --level=0 --no-sitemaps --concurrency=5 --1 --warc-max-size=524288000 --wpull-args="--no-check-certificate --timeout=300"
<arkiver>that works
<arkiver>~/.local/bin/grab-site http://www.eqmweekly.com.af/technology/8287-پشت-پرده‌‏ی-قتل-عام-در-نایجریا --level=0 --no-sitemaps --concurrency=5 --1 --warc-max-size=524288000 --wpull-args="--no-check-certificate --timeout=300"
<arkiver>that does not work
```

grab-site passes the URLs to wpull. The first line works, but the second line gives this error:
```
Traceback (most recent call last):
  File "/home/arkiver/.local/bin/grab-site", line 4, in <module>
    main.main()
  File "/home/arkiver/.local/lib/python3.4/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/arkiver/.local/lib/python3.4/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/arkiver/.local/lib/python3.4/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/arkiver/.local/lib/python3.4/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/arkiver/.local/lib/python3.4/site-packages/libgrabsite/main.py", line 307, in main
    wpull.__main__.main()
  File "/home/arkiver/.local/lib/python3.4/site-packages/wpull/__main__.py", line 29, in main
    builder.build()
  File "/home/arkiver/.local/lib/python3.4/site-packages/wpull/builder.py", line 208, in build
    for url_info in self._build_input_urls():
  File "/home/arkiver/.local/lib/python3.4/site-packages/wpull/builder.py", line 524, in _build_input_urls
    url_string, default_scheme=default_scheme)
  File "/usr/lib/python3.4/functools.py", line 452, in wrapper
    result = user_function(*args, **kwds)
  File "/home/arkiver/.local/lib/python3.4/site-packages/wpull/url.py", line 128, in parse
    raise ValueError('URL is not printable: {}'.format(ascii(url)))
ValueError: URL is not printable: 'http://www.eqmweekly.com.af/technology/8287-\u067e\u0634\u062a-\u067e\u0631\u062f\u0647\u200c\u200f\u06cc-\u0642\u062a\u0644-\u0639\u0627\u0645-\u062f\u0631-\u0646\u0627\u06cc\u062c\u0631\u06cc\u0627'
```
This can be fixed by encoding the URL from the second line.

**Comment by ivan** [comment]
Also leads to some URLs not getting crawled in a crawl that *does* start: https://github.com/ludios/grab-site/issues/11
