### ISSUE TITLE
NameError: name '__iter__' is not defined

### ISSUE THREAD

**Issue by kergoth** [chfoo/wpull#305]
Seen when running just 'wpull' after installing into a virtualenv using python 3.5. Full traceback:
```
Traceback (most recent call last):
  File "/Users/kergoth/.local/share/virtualenvs/wpull/bin/wpull", line 2, in <module>
    import wpull.__main__
  File "/Users/kergoth/.local/share/virtualenvs/wpull/lib/python3.5/site-packages/wpull/__main__.py", line 7, in <module>
    import trollius
  File "/Users/kergoth/.local/share/virtualenvs/wpull/lib/python3.5/site-packages/trollius/__init__.py", line 21, in <module>
    from .base_events import *
  File "/Users/kergoth/.local/share/virtualenvs/wpull/lib/python3.5/site-packages/trollius/base_events.py", line 39, in <module>
    from . import coroutines
  File "/Users/kergoth/.local/share/virtualenvs/wpull/lib/python3.5/site-packages/trollius/coroutines.py", line 15, in <module>
    from . import futures
  File "/Users/kergoth/.local/share/virtualenvs/wpull/lib/python3.5/site-packages/trollius/futures.py", line 116, in <module>
    class Future(object):
  File "/Users/kergoth/.local/share/virtualenvs/wpull/lib/python3.5/site-packages/trollius/futures.py", line 426, in Future
    __await__ = __iter__ # make compatible with 'await' expression
NameError: name '__iter__' is not defined
```

Is there a specific version of trollius needed?

**Comment by kergoth** [comment]
Nevermind, found https://github.com/haypo/trollius/issues/4 -- seems it must not be in a release yet, since pip didn't pick up their fix.
