### ISSUE TITLE
wpull.database.base.NotFound during converting links

### ISSUE THREAD

**Issue by TheMattt** [chfoo/wpull#312]
OSX El Capitan 10.11.3
Python 3.4.4
wpull version 1.2.3

I'm attempting to run wpull with the following parameters, but it errors out during the "converting links" step. The domain is somewhat arbitrary as I'm getting the exact same error on other domains too.

`wpull www.sandpiperqueenanne.com --warc-file archive --page-requisites --recursive --level inf --span-hosts-allow page-requisites --convert-links
`
```
INFO Converting links in file ‘www.sandpiperqueenanne.com/index.html’ (type=html).
INFO Converting links in file ‘www.sandpiperqueenanne.com/vacancy.html’ (type=html).
INFO Converting links in file ‘www.sandpiperqueenanne.com/assets/css/bootstrap-responsive.css’ (type=css).
INFO Converting links in file ‘www.sandpiperqueenanne.com/index.html’ (type=html).
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/bin/wpull", line 3, in <module>
    wpull.__main__.main()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/wpull/__main__.py", line 40, in main
    exit_code = application.run_sync()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/wpull/app.py", line 118, in run_sync
    return self._event_loop.run_until_complete(self.run())
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/trollius/base_events.py", line 350, in run_until_complete
    return future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/trollius/futures.py", line 287, in result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/trollius/tasks.py", line 259, in _step
    result = coro.send(value)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/wpull/app.py", line 171, in run
    self._convert_documents()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/wpull/app.py", line 275, in _convert_documents
    converter.convert_all()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/wpull/converter.py", line 58, in convert_all
    self.convert_by_record(url_record)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/wpull/converter.py", line 98, in convert_by_record
    filename, temp_filename, base_url=url_record.url)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/wpull/converter.py", line 162, in convert
    self._convert_element(element, is_xhtml=is_xhtml)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/wpull/converter.py", line 185, in _convert_element
    new_value = self._convert_css_attrib(link_info)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/wpull/converter.py", line 246, in _convert_css_attrib
    text, base_url=self._base_url
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/wpull/converter.py", line 304, in convert_text
    text_list.append(self.get_new_url(text, base_url))
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/wpull/converter.py", line 314, in get_new_url
    url_record = self._url_table.get_one(url)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/wpull/database/wrap.py", line 33, in get_one
    return self.url_table.get_one(url)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/wpull/database/sqltable.py", line 52, in get_one
    raise NotFound()
wpull.database.base.NotFound
Exception ignored in: <bound method _UnixSelectorEventLoop.__del__ of <_UnixSelectorEventLoop running=False closed=True debug=False>>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/trollius/base_events.py", line 395, in __del__
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/trollius/unix_events.py", line 65, in close
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/trollius/unix_events.py", line 166, in remove_signal_handler
TypeError: signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object
```
----
Edited by chfoo for log formatting

**Comment by hoogenm** [comment]
Same on Linux (Ubuntu based 14.04), tested with Python 3.4 and also Python 3.3 (3.3.6).
Both in a `virtualenv` environment. wpull version 1.2.3. Also tried with 1.2.2, same error.
This package seems very nice and useful, too bad there does not seem to be a work-around for the NotFound() error.
