### ISSUE TITLE
AssertionError: Expect conn created. Got dead. Was: Wpull crashes (this is run by ArchiveTeam/ftp-grab)

### ISSUE THREAD

**Issue by luckcolors** [chfoo/wpull#318]
I'm trying to run ftb-grab and wpull throws this error:

```
ERROR Fatal exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/wpull/app.py", line 128, in run
    yield From(self._builder.factory['Engine']())
  File "<string>", line 29, in pep479_wrapped
  File "/usr/local/lib/python3.5/site-packages/trollius/tasks.py", line 257, in _step
    result = coro.throw(exc)
  File "<string>", line 11, in pep479_wrapped
  File "/usr/local/lib/python3.5/site-packages/wpull/engine.py", line 281, in __call__
    yield From(self._run_workers())
  File "<string>", line 29, in pep479_wrapped
  File "/usr/local/lib/python3.5/site-packages/trollius/tasks.py", line 259, in _step
    result = coro.send(value)
  File "<string>", line 13, in pep479_wrapped
  File "/usr/local/lib/python3.5/site-packages/wpull/engine.py", line 70, in _run_workers
    task.result()
  File "/usr/local/lib/python3.5/site-packages/trollius/futures.py", line 287, in result
    raise self._exception
  File "/usr/local/lib/python3.5/site-packages/trollius/tasks.py", line 257, in _step
    result = coro.throw(exc)
  File "<string>", line 11, in pep479_wrapped
  File "/usr/local/lib/python3.5/site-packages/wpull/engine.py", line 149, in _run_worker
    yield From(self._process_item(item))
  File "<string>", line 29, in pep479_wrapped
  File "/usr/local/lib/python3.5/site-packages/trollius/tasks.py", line 257, in _step
    result = coro.throw(exc)
  File "<string>", line 11, in pep479_wrapped
  File "/usr/local/lib/python3.5/site-packages/wpull/engine.py", line 330, in _process_item
    yield From(self._process_url_item(url_record))
  File "<string>", line 29, in pep479_wrapped
  File "/usr/local/lib/python3.5/site-packages/trollius/tasks.py", line 257, in _step
    result = coro.throw(exc)
  File "<string>", line 11, in pep479_wrapped
  File "/usr/local/lib/python3.5/site-packages/wpull/engine.py", line 387, in _process_url_item
    yield From(self._processor.process(url_item))
  File "<string>", line 29, in pep479_wrapped
  File "/usr/local/lib/python3.5/site-packages/trollius/tasks.py", line 257, in _step
    result = coro.throw(exc)
  File "<string>", line 11, in pep479_wrapped
  File "/usr/local/lib/python3.5/site-packages/wpull/processor/delegate.py", line 29, in process
    raise Return((yield From(self.ftp_processor.process(url_item))))
  File "<string>", line 29, in pep479_wrapped
  File "/usr/local/lib/python3.5/site-packages/trollius/tasks.py", line 257, in _step
    result = coro.throw(exc)
  File "<string>", line 11, in pep479_wrapped
  File "/usr/local/lib/python3.5/site-packages/wpull/processor/ftp.py", line 133, in process
    raise Return((yield From(session.process())))
  File "<string>", line 29, in pep479_wrapped
  File "/usr/local/lib/python3.5/site-packages/trollius/tasks.py", line 257, in _step
    result = coro.throw(exc)
  File "<string>", line 11, in pep479_wrapped
  File "/usr/local/lib/python3.5/site-packages/wpull/processor/ftp.py", line 184, in process
    is_file = yield From(self._prepare_request_file_vs_dir(request))
  File "<string>", line 29, in pep479_wrapped
  File "/usr/local/lib/python3.5/site-packages/trollius/tasks.py", line 257, in _step
    result = coro.throw(exc)
  File "<string>", line 11, in pep479_wrapped
  File "/usr/local/lib/python3.5/site-packages/wpull/processor/ftp.py", line 208, in _prepare_request_file_vs_dir
    files = yield From(self._fetch_parent_path(request))
  File "<string>", line 29, in pep479_wrapped
  File "/usr/local/lib/python3.5/site-packages/trollius/tasks.py", line 257, in _step
    result = coro.throw(exc)
  File "<string>", line 11, in pep479_wrapped
  File "/usr/local/lib/python3.5/site-packages/wpull/processor/ftp.py", line 252, in _fetch_parent_path
    yield From(session.fetch_file_listing(directory_request))
  File "<string>", line 29, in pep479_wrapped
  File "/usr/local/lib/python3.5/site-packages/trollius/tasks.py", line 257, in _step
    result = coro.throw(exc)
  File "<string>", line 11, in pep479_wrapped
  File "/usr/local/lib/python3.5/site-packages/wpull/ftp/client.py", line 151, in fetch_file_listing
    yield From(self._prepare_fetch(request, response))
  File "<string>", line 29, in pep479_wrapped
  File "/usr/local/lib/python3.5/site-packages/trollius/tasks.py", line 257, in _step
    result = coro.throw(exc)
  File "<string>", line 11, in pep479_wrapped
  File "/usr/local/lib/python3.5/site-packages/wpull/ftp/client.py", line 205, in _prepare_fetch
    yield From(self._log_in())
  File "<string>", line 29, in pep479_wrapped
  File "/usr/local/lib/python3.5/site-packages/trollius/tasks.py", line 257, in _step
    result = coro.throw(exc)
  File "<string>", line 11, in pep479_wrapped
  File "/usr/local/lib/python3.5/site-packages/wpull/ftp/client.py", line 95, in _log_in
    yield From(self._commander.login(username, password))
  File "<string>", line 29, in pep479_wrapped
  File "/usr/local/lib/python3.5/site-packages/trollius/tasks.py", line 257, in _step
    result = coro.throw(exc)
  File "<string>", line 11, in pep479_wrapped
  File "/usr/local/lib/python3.5/site-packages/wpull/ftp/command.py", line 67, in login
    yield From(self._control_stream.write_command(Command('USER', username)))
  File "<string>", line 29, in pep479_wrapped
  File "/usr/local/lib/python3.5/site-packages/trollius/tasks.py", line 257, in _step
    result = coro.throw(exc)
  File "<string>", line 11, in pep479_wrapped
  File "<string>", line 11, in pep479_wrapped
  File "/usr/local/lib/python3.5/site-packages/wpull/abstract/stream.py", line 16, in wrapper
    raise Return((yield From(func(self, *args, **kwargs))))
  File "<string>", line 29, in pep479_wrapped
  File "<string>", line 29, in pep479_wrapped
  File "/usr/local/lib/python3.5/site-packages/trollius/tasks.py", line 257, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.5/site-packages/wpull/ftp/stream.py", line 125, in write_command
    yield From(self._connection.write(data))
  File "/usr/local/lib/python3.5/site-packages/trollius/tasks.py", line 259, in _step
    result = coro.send(value)
  File "<string>", line 15, in pep479_wrapped
  File "/usr/local/lib/python3.5/site-packages/wpull/connection.py", line 534, in write
    'Expect conn created. Got {}.'.format(self._state)
AssertionError: Expect conn created. Got dead.
CRITICAL Sorry, Wpull unexpectedly crashed.
CRITICAL Please report this problem to the authors at Wpull's issue tracker so it may be fixed. If you know how to program, maybe help us fix it? Thank you for helping us help you help us all.
```

**Comment by A4136** [comment]
Might be problem with Python 3.5? Works fine on 3.4 but crashes with 3.5.

**Comment by luckcolors** [comment]
It may be but i can't test on the server as i would have to uninstall python35 and it's currently used by some scripts.

**Comment by ivan** [comment]
Yeah, the traceback indicates this is a Python 3.5-only problem.  python3.4 and python3.5 can coexist on the same machine.  (There's pyenv, and for Ubuntu, the deadsnakes PPA.)

**Comment by ivan** [comment]
https://github.com/chfoo/wpull/issues/290
