### ISSUE TITLE
wpull 2.0 KeyError: 'ResourceMonitor' crash without psutil installed

### ISSUE THREAD

**Issue by ivan** [chfoo/wpull#327]
In a clean user account with no Python 3.5 packages installed:

```
# pip3 install --user wpull
[...]
# ~/.local/bin/wpull3 http://example.com/
psutil: No module named 'psutil'. Resource monitoring will be unavailable.
INFO Fetching ‘http://example.com/’.
  100.0% [=========================] 1.2 KiB 0:00:00 6.0 KiB/s
INFO Fetched ‘http://example.com/’: 200 OK. Length: 1270 [text/html].
ERROR Fatal exception.
Traceback (most recent call last):
  File "/home/wpull2/.local/lib/python3.5/site-packages/wpull/application/app.py", line 152, in run
    yield from pipeline.process()
  File "/home/wpull2/.local/lib/python3.5/site-packages/wpull/pipeline/pipeline.py", line 194, in process
    yield from self._process_one_worker()
  File "/home/wpull2/.local/lib/python3.5/site-packages/wpull/pipeline/pipeline.py", line 215, in _process_one_worker
    task.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 240, in _step
    result = coro.send(None)
  File "/home/wpull2/.local/lib/python3.5/site-packages/wpull/pipeline/pipeline.py", line 119, in process
    item = yield from self.process_one(_worker_id=worker_id)
  File "/home/wpull2/.local/lib/python3.5/site-packages/wpull/pipeline/pipeline.py", line 103, in process_one
    yield from task.process(item)
  File "/home/wpull2/.local/lib/python3.5/site-packages/wpull/application/tasks/resmon.py", line 41, in process
    resource_monitor = session.app_session.factory['ResourceMonitor']
  File "/home/wpull2/.local/lib/python3.5/site-packages/wpull/application/factory.py", line 37, in __getitem__
    return self._instance_map[key]
KeyError: 'ResourceMonitor'
CRITICAL Sorry, Wpull unexpectedly crashed.
CRITICAL Please report this problem to the authors at Wpull's issue tracker so it may be fixed. If you know how to program, maybe help us fix it? Thank you for helping us help you help us all.
INFO Exiting with status 1.
Exception ignored in: <generator object HappyEyeballsConnection._connect_dual_stack.<locals>.cleanup at 0x7f6b48dd5d00>
Traceback (most recent call last):
  File "/home/wpull2/.local/lib/python3.5/site-packages/wpull/network/pool.py", line 427, in cleanup
    conn = yield from fut
  File "/usr/lib/python3.5/asyncio/tasks.py", line 489, in _wait_for_one
    f = yield from done.get()
  File "/usr/lib/python3.5/asyncio/queues.py", line 170, in get
    getter.cancel()  # Just in case getter is not done yet.
  File "/usr/lib/python3.5/asyncio/futures.py", line 227, in cancel
    self._schedule_callbacks()
  File "/usr/lib/python3.5/asyncio/futures.py", line 242, in _schedule_callbacks
    self._loop.call_soon(callback, self)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 483, in call_soon
    handle = self._call_soon(callback, args)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 492, in _call_soon
    self._check_closed()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 320, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**Comment by Asparagirl** [comment]
I get this too. I added ```pip3 install psutil``` after installing wpull, which at least gets rid of the warning, but I'm still having other issues, not sure if related.
