### ISSUE TITLE
wpull does not exit after ctrl-c

### ISSUE THREAD

**Issue by ivan** [chfoo/wpull#330]
Pressing ctrl-c in wpull 2.0 does not seem to ever exit the process:

```
# ~/.local/bin/wpull3 --version
2.0.1

# python3 --version
Python 3.5.1+

# uname -srv
Linux 4.4.0-24-generic #43-Ubuntu SMP Wed Jun 8 19:27:37 UTC 2016

# ~/.local/bin/wpull3 -r https://github.com/
  100.0% [=========================] 29.8 KiB 0:00:00 11.2 KiB/s
INFO Fetching ‘https://github.com/’.

INFO Fetched ‘https://github.com/’: 200 OK. Length: unspecified [text/html; charset=utf-8].
INFO Fetching ‘https://github.com/signup_check/username’.
  [O                        ] 74.9 KiB 0:00:00 7.5 B/s
INFO Fetched ‘https://github.com/signup_check/username’: 404 Not Found. Length: unspecified [text/html; charset=utf-8].
INFO Fetching ‘https://github.com/security’.
  100.0% [=========================] 115.0 B 0:00:01 101.4 B/s
INFO Fetched ‘https://github.com/security’: 301 Moved Permanently. Length: 115 [text/html].
INFO Fetching ‘https://help.github.com/articles/github-security/’.
  100.0% [=========================] 13.7 KiB 0:00:01 3.0 KiB/s
INFO Fetched ‘https://help.github.com/articles/github-security/’: 200 OK. Length: 14005 [text/html; charset=utf-8].
INFO Fetching ‘https://github.com/about’.

INFO Fetched ‘https://github.com/about’: 200 OK. Length: unspecified [text/html; charset=utf-8].
INFO Fetching ‘https://github.com/business’.

INFO Fetched ‘https://github.com/business’: 200 OK. Length: unspecified [text/html; charset=utf-8].
^CINFO Fetching ‘https://github.com/login’.
INFO Stopping once all requests complete...
INFO Interrupt again to force stopping immediately.
  [O                        ] 5.0 B 0:00:01 2.7 B/s
INFO Fetched ‘https://github.com/login’: 200 OK. Length: unspecified [text/html; charset=utf-8].
```

Pressing ctrl-c again shows this, and does exit:

```
^CINFO Forcing immediate stop...
Traceback (most recent call last):
  File "/home/wpull2/.local/bin/wpull3", line 9, in <module>
    load_entry_point('wpull==2.0.1', 'console_scripts', 'wpull3')()
  File "/home/wpull2/.local/lib/python3.5/site-packages/wpull/application/main.py", line 27, in main
    exit_code = application.run_sync()
  File "/home/wpull2/.local/lib/python3.5/site-packages/wpull/application/app.py", line 132, in run_sync
    exit_status = asyncio.get_event_loop().run_until_complete(self.run())
  File "/usr/lib/python3.5/asyncio/base_events.py", line 371, in run_until_complete
    raise RuntimeError('Event loop stopped before Future completed.')
RuntimeError: Event loop stopped before Future completed.
Exception ignored in: <bound method BaseEventLoop.__del__ of <_UnixSelectorEventLoop running=False closed=True debug=False>>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/base_events.py", line 417, in __del__
  File "/usr/lib/python3.5/asyncio/unix_events.py", line 58, in close
  File "/usr/lib/python3.5/asyncio/unix_events.py", line 139, in remove_signal_handler
  File "/usr/lib/python3.5/signal.py", line 47, in signal
TypeError: signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object
```

**Comment by JustAnotherArchivist** [comment]
Maybe fixed by 2778442c in #348?
