### ISSUE TITLE
Unexpected Crash

### ISSUE THREAD

**Issue by matthusby** [chfoo/wpull#352]
*What I expect:* Shouldn't crash

*Operating system:* `Linux frogger 4.8.0-37-generic #39-Ubuntu SMP Thu Jan 26 02:27:07 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

*Python version:* `Python 2.7.12+`

*Wpull version:* `2.0.1`

*Log/Output:* 

```
Traceback (most recent call last):
  File "site-packages/wpull/application/app.py", line 152, in run
  File "site-packages/wpull/pipeline/pipeline.py", line 194, in process
  File "site-packages/wpull/pipeline/pipeline.py", line 215, in _process_one_worker
  File "asyncio/futures.py", line 275, in result
  File "asyncio/tasks.py", line 236, in _step
  File "site-packages/wpull/pipeline/pipeline.py", line 119, in process
  File "site-packages/wpull/pipeline/pipeline.py", line 103, in process_one
  File "site-packages/wpull/application/tasks/download.py", line 492, in process
  File "site-packages/wpull/processor/delegate.py", line 29, in process
  File "site-packages/wpull/processor/ftp.py", line 100, in process
  File "site-packages/wpull/processor/ftp.py", line 147, in process
  File "site-packages/wpull/processor/ftp.py", line 183, in _prepare_request_file_vs_dir
  File "site-packages/wpull/processor/ftp.py", line 243, in _fetch_parent_path
  File "site-packages/wpull/protocol/abstract/client.py", line 53, in __exit__
  File "site-packages/wpull/protocol/ftp/client.py", line 410, in recycle
  File "site-packages/wpull/application/hook.py", line 134, in notify
  File "site-packages/wpull/warc/recorder.py", line 665, in end_control
  File "site-packages/wpull/warc/recorder.py", line 714, in _request_hostname_port
AttributeError: 'NoneType' object has no attribute 'address'
CRITICAL Sorry, Wpull unexpectedly crashed.
CRITICAL Please report this problem to the authors at Wpull's issue tracker so it may be fixed. If you know how to program, maybe help us fix it? Thank you for helping us help you help us all.
INFO Exiting with status 1.
Process WgetDownload returned exit code 1 for Item newsbuddy:goldsmr4.sci.gsfc.nasa.gov_78159
Failed WgetDownload for Item newsbuddy:goldsmr4.sci.gsfc.nasa.gov_78159

```

**Comment by jcj83429** [comment]
This is also from ftp-gov-grab

	ERROR Fatal exception.
	Traceback (most recent call last):
	  File "site-packages/wpull/network/connection.py", line 299, in run_network_operation
	  File "asyncio/tasks.py", line 377, in wait_for
	  File "asyncio/futures.py", line 275, in result
	  File "asyncio/tasks.py", line 234, in _step
	  File "asyncio/streams.py", line 63, in open_connection
	  File "asyncio/base_events.py", line 625, in create_connection
	  File "asyncio/base_events.py", line 612, in create_connection
	  File "asyncio/futures.py", line 386, in __iter__
	  File "asyncio/tasks.py", line 287, in _wakeup
	  File "asyncio/futures.py", line 275, in result
	  File "asyncio/selector_events.py", line 438, in _sock_connect_cb
	OSError: [Errno 101] Connect call failed ('192.111.123.134', 21)

	The above exception was the direct cause of the following exception:

	Traceback (most recent call last):
	  File "site-packages/wpull/processor/ftp.py", line 265, in _fetch
	  File "site-packages/wpull/protocol/ftp/client.py", line 132, in start
	  File "site-packages/wpull/protocol/ftp/client.py", line 216, in _prepare_fetch
	  File "site-packages/wpull/protocol/ftp/stream.py", line 100, in reconnect
	  File "site-packages/wpull/network/pool.py", line 382, in connect
	  File "site-packages/wpull/network/connection.py", line 194, in connect
	  File "site-packages/wpull/network/connection.py", line 335, in run_network_operation
	wpull.errors.NetworkError: [Errno 101] Network is unreachable

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	  File "site-packages/wpull/application/app.py", line 152, in run
	  File "site-packages/wpull/pipeline/pipeline.py", line 194, in process
	  File "site-packages/wpull/pipeline/pipeline.py", line 215, in _process_one_worker
	  File "asyncio/futures.py", line 275, in result
	  File "asyncio/tasks.py", line 238, in _step
	  File "site-packages/wpull/pipeline/pipeline.py", line 119, in process
	  File "site-packages/wpull/pipeline/pipeline.py", line 103, in process_one
	  File "site-packages/wpull/application/tasks/download.py", line 492, in process
	  File "site-packages/wpull/processor/delegate.py", line 29, in process
	  File "site-packages/wpull/processor/ftp.py", line 100, in process
	  File "site-packages/wpull/processor/ftp.py", line 151, in process
	  File "site-packages/wpull/processor/ftp.py", line 292, in _fetch
	  File "site-packages/wpull/protocol/abstract/client.py", line 53, in __exit__
	  File "site-packages/wpull/protocol/ftp/client.py", line 410, in recycle
	  File "site-packages/wpull/application/hook.py", line 134, in notify
	  File "site-packages/wpull/warc/recorder.py", line 665, in end_control
	  File "site-packages/wpull/warc/recorder.py", line 714, in _request_hostname_port
	AttributeError: 'NoneType' object has no attribute 'address'
	CRITICAL Sorry, Wpull unexpectedly crashed.
	CRITICAL Please report this problem to the authors at Wpull's issue tracker so it may be fixed. If you know how to program, maybe help us fix it? Thank you for helping us help you help us all.
	INFO Exiting with status 1.

**Comment by JustAnotherArchivist** [comment]
This happens when wpull tries to grab an FTP URL whose domain does not resolve. E.g. ArchiveBot job emwqytj03lzi8igsg5n95t596 crashed last night because it tried to grab something from ftp://ftp.fao.org/, which no longer exists (NXDOMAIN).
