### ISSUE TITLE
convert-links crashes wpull trying to convert "‘./robots.txt’ (type=None)"

### ISSUE THREAD

**Issue by SpiritQuaddicted** [chfoo/wpull#357]
$ ~/.local/bin/wpull3 --no-robots --adjust-extension --convert-links http://www.isratrance.com/robots.txt
psutil: No module named 'psutil'. Resource monitoring will be unavailable.
INFO Fetching ‘http://www.isratrance.com/robots.txt’.
  100.0% [=========================] 226.0 B 0:00:00 252.5 B/s
INFO Fetched ‘http://www.isratrance.com/robots.txt’: 200 OK. Length: 226 [text/plain].
INFO FINISHED.
INFO Duration: 0:00:02. Speed: 80.8 B/s.
INFO Downloaded: 1 file, 226.0 B.
INFO Converting links in file ‘./robots.txt’ (type=None).
ERROR Fatal exception.
Traceback (most recent call last):
  File "/home/me/.local/lib/python3.4/site-packages/wpull/application/app.py", line 152, in run
    yield from pipeline.process()
  File "/home/me/.local/lib/python3.4/site-packages/wpull/pipeline/pipeline.py", line 194, in process
    yield from self._process_one_worker()
  File "/home/me/.local/lib/python3.4/site-packages/wpull/pipeline/pipeline.py", line 215, in _process_one_worker
    task.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 237, in _step
    result = next(coro)
  File "/home/me/.local/lib/python3.4/site-packages/wpull/pipeline/pipeline.py", line 119, in process
    item = yield from self.process_one(_worker_id=worker_id)
  File "/home/me/.local/lib/python3.4/site-packages/wpull/pipeline/pipeline.py", line 103, in process_one
    yield from task.process(item)
  File "/usr/lib/python3.4/asyncio/coroutines.py", line 141, in coro
    res = func(*args, **kw)
  File "/home/me/.local/lib/python3.4/site-packages/wpull/application/tasks/conversion.py", line 69, in process
    converter.convert_by_record(session.url_record)
  File "/home/me/.local/lib/python3.4/site-packages/wpull/converter.py", line 99, in convert_by_record
    raise Exception('Unknown link type.')
Exception: Unknown link type.
CRITICAL Sorry, Wpull unexpectedly crashed.
CRITICAL Please report this problem to the authors at Wpull's issue tracker so it may be fixed. If you know how to program, maybe help us fix it? Thank you for helping us help you help us all.
INFO Exiting with status 1.

$ ~/.local/bin/wpull3 --version
psutil: No module named 'psutil'. Resource monitoring will be unavailable.
2.0.1

$ python3 --version
Python 3.4.2

**Comment by kannes** [comment]
Another test case: https://gbatemp.net/robots.txt
