### ISSUE TITLE
sqlite3.OperationalError: Safety level may not be changed inside a transaction

### ISSUE THREAD

**Issue by SpiritQuaddicted** [chfoo/wpull#362]
I cannot download any URL with wpull anymore. Always getting "sqlite3.OperationalError: Safety level may not be changed inside a transaction".

pip says wpull==2.0.1 (installed via pip)
pip says SQLAlchemy==1.1.8 (installed via Archlinux package)
python is Python 3.6.0
sqlite3 is 3.17.0 2017-02-13 16:02:40 ada05cfa86ad7f5645450ac7a2a21c9aa6e57d2c
I am on 64bit Archlinux, all packages up to date.

```
$ ~/.local/bin/wpull3 https://www.github.com
ERROR Fatal exception.
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2139, in _wrap_pool_connect
    return fn()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/pool.py", line 397, in connect
    return _ConnectionFairy._checkout(self, self._threadconns)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/pool.py", line 766, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/pool.py", line 516, in checkout
    rec = pool._do_get()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/pool.py", line 1045, in _do_get
    c = self._create_connection()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/pool.py", line 333, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/pool.py", line 461, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/pool.py", line 663, in __connect
    pool.dispatch.connect(self.connection, self)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/event/attr.py", line 256, in __call__
    fn(*args, **kw)
  File "/home/user/.local/lib/python3.6/site-packages/wpull/database/sqltable.py", line 292, in _apply_pragmas_callback
    connection.execute('PRAGMA synchronous=NORMAL')
sqlite3.OperationalError: Safety level may not be changed inside a transaction

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.6/site-packages/wpull/application/app.py", line 152, in run
    yield from pipeline.process()
  File "/home/user/.local/lib/python3.6/site-packages/wpull/pipeline/pipeline.py", line 194, in process
    yield from self._process_one_worker()
  File "/home/user/.local/lib/python3.6/site-packages/wpull/pipeline/pipeline.py", line 215, in _process_one_worker
    task.result()
  File "/home/user/.local/lib/python3.6/site-packages/wpull/pipeline/pipeline.py", line 119, in process
    item = yield from self.process_one(_worker_id=worker_id)
  File "/home/user/.local/lib/python3.6/site-packages/wpull/pipeline/pipeline.py", line 103, in process_one
    yield from task.process(item)
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 210, in coro
    res = func(*args, **kw)
  File "/home/user/.local/lib/python3.6/site-packages/wpull/application/tasks/database.py", line 30, in process
    'URLTableImplementation', path=session.args.database)
  File "/home/user/.local/lib/python3.6/site-packages/wpull/application/factory.py", line 60, in new
    instance = self._class_map[name](*args, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/wpull/database/sqltable.py", line 281, in __init__
    DBBase.metadata.create_all(self._engine)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 3885, in create_all
    tables=tables)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1920, in _run_visitor
    with self._optional_conn_ctx_manager(connection) as conn:
  File "/usr/lib/python3.6/contextlib.py", line 82, in __enter__
    return next(self.gen)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1913, in _optional_conn_ctx_manager
    with self.contextual_connect() as conn:
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2104, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2143, in _wrap_pool_connect
    e, dialect, self)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1457, in _handle_dbapi_exception_noconnection
    exc_info
  File "/usr/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2139, in _wrap_pool_connect
    return fn()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/pool.py", line 397, in connect
    return _ConnectionFairy._checkout(self, self._threadconns)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/pool.py", line 766, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/pool.py", line 516, in checkout
    rec = pool._do_get()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/pool.py", line 1045, in _do_get
    c = self._create_connection()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/pool.py", line 333, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/pool.py", line 461, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/pool.py", line 663, in __connect
    pool.dispatch.connect(self.connection, self)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/event/attr.py", line 256, in __call__
    fn(*args, **kw)
  File "/home/user/.local/lib/python3.6/site-packages/wpull/database/sqltable.py", line 292, in _apply_pragmas_callback
    connection.execute('PRAGMA synchronous=NORMAL')
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) Safety level may not be changed inside a transaction
CRITICAL Sorry, Wpull unexpectedly crashed.
CRITICAL Please report this problem to the authors at Wpull's issue tracker so it may be fixed. If you know how to program, maybe help us fix it? Thank you for helping us help you help us all.
INFO Exiting with status 1.

```

**Comment by fabiommendes** [comment]
Same problem here (I'm also using Archlinux). I downgraded SQLAlchemy to 1.0.13 and the error still persists.  Have you tried wpull with Python 3.6?

**Comment by tiagofassoni** [comment]
I'm not the bug issuer, but I have the same error, and yes, with Python 3.6

**Comment by tiagofassoni** [comment]
Found out the problem. At the sqltable.py file, in the function _apply_pragmas_callback, 'PRAGMA synchronous=NORMAL' must be called first.

If there is interest, I can make it into a pull request.

**Comment by chfoo** [comment]
Thanks for looking into it. Yes, feel free to make pull request to remind me when I start work on this again in the future. (Ignore the Travis CI errors since it's broken right now)

**Comment by tiagofassoni** [comment]
Okay, will do. Also, I need to do another pull request to solve the issue of the html5lib changing some of its methods to private.

**Comment by ChuhC** [comment]
same error with python 3.6.0 ,wpull 2.0.1,  tornado 4.5 and html5lib==0.9999999.  Is it solved now ?

**Comment by JustAnotherArchivist** [comment]
I'm not seeing this error on a Debian Stretch machine with Python 3.5.3-1+deb9u1, wpull 2.0.3, SQLAlchemy 1.3.4, and libsqlite3-0 3.16.2-5+deb9u1. This probably depends on either the SQLite version or the SQLAlchemy one. @ChuhC, which ones are you using?

I don't see anything inherently wrong with setting the `PRAGMA`s in this order, and I couldn't find anything in the SQLite documentation either that would prohibit this. Neither of the `PRAGMA` statements opens a transaction. I suspect that SQLAlchemy is interfering somehow.

**Comment by jodizzle** [comment]
I'm seeing this error as well.

- OS: Arch Linux 64-bit
- wpull version: Commit a4ff4a93f613ce18ad3c515aa3d4f5848a88b98c (current HEAD of the `develop` branch)
- SQLite version: 3.30.1
- Python version: 3.6.0
- Packages: Installed from requirements.txt into a virtualenv.  `pip freeze`:
```
chardet==2.3.0
dnspython3==1.12.0
html5lib==0.999999999
lxml==3.5.0
namedlist==1.7
psutil==4.2.0
six==1.12.0
SQLAlchemy==1.0.13
tornado==4.5.3
typing==3.5.1.0
webencodings==0.5.1
-e git+https://github.com/archiveteam/wpull@a4ff4a93f613ce18ad3c515aa3d4f5848a88b98c#egg=wpull
Yapsy==1.11.223
```

I've also tried SQLAlchemy versions 0.9.0 (minimum specified in the requirements.txt) and 1.3.4 (from the [previous comment on this ticket](https://github.com/ArchiveTeam/wpull/issues/362#issuecomment-505213807)).  Both give the same results.  Given this, I'm guessing there's an issue with my SQLite version.
