### ISSUE TITLE
Wpull crashes if there are empty lines in a list

### ISSUE THREAD

**Issue by DoomTay** [chfoo/wpull#375]
*What I wanted:* To grab each URL from a text file containing a list of URLs
 
*What I expect:* Grab the front page of each URL in the list

*What happened:* wpull crashes without grabbing anything

*The command or website causes the problem:* wpull --output-file log.txt -i testthing.txt --ignore-fatal-errors

[testthing.txt](https://github.com/chfoo/wpull/files/1288593/testthing.txt)

*Operating system:* Windows 10

*Python version:* (What does `python --version` say?) Python 3.5.2

*Wpull version:* (What does `wpull --version` say?) 2.0.1

*Log/Output:*

```
Graceful stopping with Unix signals is not supported on this OS.
WARNING Certificate directory /etc/ssl/certs/ does not exist.
WARNING Certificate file /etc/ssl/certs/ca-certificates.crt does not exist.
ERROR Fatal exception.
Traceback (most recent call last):
  File "c:\users\taylor\appdata\local\programs\python\python35-32\lib\site-packages\wpull\application\app.py", line 152, in run
    yield from pipeline.process()
  File "c:\users\taylor\appdata\local\programs\python\python35-32\lib\site-packages\wpull\pipeline\pipeline.py", line 194, in process
    yield from self._process_one_worker()
  File "c:\users\taylor\appdata\local\programs\python\python35-32\lib\site-packages\wpull\pipeline\pipeline.py", line 215, in _process_one_worker
    task.result()
  File "c:\users\taylor\appdata\local\programs\python\python35-32\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "c:\users\taylor\appdata\local\programs\python\python35-32\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "c:\users\taylor\appdata\local\programs\python\python35-32\lib\site-packages\wpull\pipeline\pipeline.py", line 119, in process
    item = yield from self.process_one(_worker_id=worker_id)
  File "c:\users\taylor\appdata\local\programs\python\python35-32\lib\site-packages\wpull\pipeline\pipeline.py", line 103, in process_one
    yield from task.process(item)
  File "c:\users\taylor\appdata\local\programs\python\python35-32\lib\asyncio\coroutines.py", line 206, in coro
    res = func(*args, **kw)
  File "c:\users\taylor\appdata\local\programs\python\python35-32\lib\site-packages\wpull\application\tasks\database.py", line 45, in process
    for batch in wpull.util.grouper(self._read_input_urls(session), 1000):
  File "c:\users\taylor\appdata\local\programs\python\python35-32\lib\site-packages\wpull\application\tasks\database.py", line 80, in _read_input_urls
    url_string, default_scheme=default_scheme)
  File "c:\users\taylor\appdata\local\programs\python\python35-32\lib\site-packages\wpull\url.py", line 133, in parse
    raise ValueError('URL missing scheme: {}'.format(ascii(url)))
ValueError: URL missing scheme: ''
CRITICAL Sorry, Wpull unexpectedly crashed.
CRITICAL Please report this problem to the authors at Wpull's issue tracker so it may be fixed. If you know how to program, maybe help us fix it? Thank you for helping us help you help us all.
INFO Exiting with status 1.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "c:\users\taylor\appdata\local\programs\python\python35-32\lib\site-packages\wpull\application\tasks\sslcontext.py", line 105, in clean_certs_file
    os.remove(certs_filename)
```
On ArchiveBot, this happened with job digzs6r4cmm0bl1w87xccpnd

**Comment by JustAnotherArchivist** [comment]
This was fixed by FalconK in [commit 582fd260](https://github.com/JustAnotherArchivist/wpull/commit/582fd260def114f2a421c357d7af7c4a1adae247). With that patch, invalid URLs simply get logged (at INFO level; shouldn't that be WARNING or ERROR?) and ignored.

**Comment by JustAnotherArchivist** [comment]
Fixed in #348, but I'll leave this open because I think only logging this as an INFO is not acceptable.

There's `wpull.url.parse_url_or_log`, which logs invalid URLs as a WARNING and is used for URLs extracted from documents. But since these are user-supplied URLs, I think a more severe log level of ERROR is appropriate. Including this in `parse_url_or_log` would probably be cleanest.
