### ISSUE TITLE
TypeError: Tuple or struct_time argument required

### ISSUE THREAD

**Issue by kannes** [chfoo/wpull#376]
*What I wanted:* Webpage downloaded
 
*What I expect:* Webpage downloaded

*What happened:* Wpull crashed

*The command or website causes the problem:* https://www.wired.com/geekdad/tag/podcast/

*Operating system:* Archlinux, Debian

*Python version:* 3.6.2, 3.4.2

*Wpull version:* 2.0.1

*Log/Output:*

```
INFO Fetching ‘https://www.wired.com/geekdad/tag/podcast/’.
INFO Fetched ‘https://www.wired.com/geekdad/tag/podcast/’: 200 OK. Length: 19698 [text/xml; charset=UTF-8].
ERROR Fatal exception.
Traceback (most recent call last):
  File "/home/me/.local/lib/python3.4/site-packages/wpull/application/app.py", line 152, in run
    yield from pipeline.process()
  File "/home/me/.local/lib/python3.4/site-packages/wpull/pipeline/pipeline.py", line 194, in process
    yield from self._process_one_worker()
  File "/home/me/.local/lib/python3.4/site-packages/wpull/pipeline/pipeline.py", line 215, in _process_one_worker
    task.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 235, in _step
    result = coro.send(value)
  File "/home/me/.local/lib/python3.4/site-packages/wpull/pipeline/pipeline.py", line 119, in process
    item = yield from self.process_one(_worker_id=worker_id)
  File "/home/me/.local/lib/python3.4/site-packages/wpull/pipeline/pipeline.py", line 103, in process_one
    yield from task.process(item)
  File "/home/me/.local/lib/python3.4/site-packages/wpull/application/tasks/download.py", line 492, in process
    yield from session.app_session.factory['Processor'].process(session)
  File "/home/me/.local/lib/python3.4/site-packages/wpull/processor/delegate.py", line 29, in process
    return (yield from processor.process(item_session))
  File "/home/me/.local/lib/python3.4/site-packages/wpull/processor/web.py", line 92, in process
    return (yield from session.process())
  File "/home/me/.local/lib/python3.4/site-packages/wpull/processor/web.py", line 186, in process
    yield from self._process_loop()
  File "/home/me/.local/lib/python3.4/site-packages/wpull/processor/web.py", line 245, in _process_loop
    exit_early, wait_time = yield from self._fetch_one(cast(Request, self._item_session.request))
  File "/home/me/.local/lib/python3.4/site-packages/wpull/processor/web.py", line 309, in _fetch_one
    action = self._handle_response(request, response)
  File "/home/me/.local/lib/python3.4/site-packages/wpull/processor/web.py", line 422, in _handle_response
    filename = self._file_writer_session.save_document(response)
  File "/home/me/.local/lib/python3.4/site-packages/wpull/writer.py", line 306, in save_document
    self.set_timestamp(self._filename, cast(HTTPResponse, response))
  File "/home/me/.local/lib/python3.4/site-packages/wpull/writer.py", line 144, in set_timestamp
    last_modified = time.mktime(last_modified)
TypeError: Tuple or struct_time argument required
CRITICAL Sorry, Wpull unexpectedly crashed.
CRITICAL Please report this problem to the authors at Wpull's issue tracker so it may be fixed. If you know how to program, maybe help us fix it? Thank you for helping us help you help us all.
INFO Exiting with status 1.

```

**Comment by kannes** [comment]
Another one: https://www.wired.com/rawfile/tag/raw-meet/feed
